#!/bin/bash

#SBATCH --partition=GPU
#SBATCH --job-name=Den302
#SBATCH --ntasks-per-node=10
#SBATCH --output=output302den.out
#SBATCH -o outfileden302.log 
#SBATCH -e errfileden302.txt

#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=natalia.huitzil@cimat.mx
#

# exportar el path hacia los ejecutables de Python
export PATH=$PATH:/opt/anaconda3_titan/bin
source /home/est_posgrado_natalia.huitzil/.bashrc
conda activate compu21

hostname
date
# Ejecutar script

cd /home/est_posgrado_natalia.huitzil/ST2/Prueba30
#cd /home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8
#cd/home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8 runner.py
#/home/est_posgrado_natalia.huitzil/.conda/envs/compu21/bin/python3.8 Cluster_Prueba7_Denoising3curvGaussian.py

#python Cluster_Prueba30_UnknownOperatorV4OPP_0.py
#python Cluster_Prueba30_UnknownOperatorV4OPP_1_adam.py
python Cluster_Prueba30_UnknownOperatorV4OPP_2_sgd.py

date
