#!/bin/bash

#SBATCH --partition=GPU
#SBATCH --job-name=392debUesp
#SBATCH --ntasks-per-node=10
#SBATCH --output=output392debUesp.out
#SBATCH -o outfile392debUesp.log 
#SBATCH -e errfile392debUesp.txt

#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=natalia.huitzil@cimat.mx
#

# exportar el path hacia los ejecutables de Python
export PATH=$PATH:/opt/anaconda3_titan/bin
source /home/est_posgrado_natalia.huitzil/.bashrc
conda activate compu21

hostname
date
# Ejecutar script

#cd /home/clirlab/natalia/Prueba37/
cd /home/est_posgrado_natalia.huitzil/ST2/Prueba39/
#cd /home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8
#cd/home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8 runner.py
#/home/est_posgrado_natalia.huitzil/.conda/envs/compu21/bin/python3.8 Cluster_Prueba7_Denoising3curvGaussian.py


python Cluster_Prueba39_VectorialTotalVariation_2_18K.py


date
