#!/bin/bash

#SBATCH --partition=GPU
#SBATCH --job-name=Den293
#SBATCH --ntasks-per-node=10
#SBATCH --output=output293den.out
#SBATCH -o outfileden293.log 
#SBATCH -e errfileden293.txt

#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=natalia.huitzil@cimat.mx
#

# exportar el path hacia los ejecutables de Python
export PATH=$PATH:/opt/anaconda3_titan/bin
source /home/est_posgrado_natalia.huitzil/.bashrc
conda activate compu21

hostname
date
# Ejecutar script

cd /home/est_posgrado_natalia.huitzil/ST2/Prueba29
#cd /home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8
#cd/home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8 runner.py
#/home/est_posgrado_natalia.huitzil/.conda/envs/compu21/bin/python3.8 Cluster_Prueba7_Denoising3curvGaussian.py

#python Cluster_Prueba29_UnknownOperatorV4OPP_0.py
#python  Cluster_Prueba29_UnknownOperatorV4OPP_adam_2.py
python Cluster_Prueba29_UnknownOperatorV4OPP_LBFGS_3.py

date
