#!/bin/bash

#SBATCH --partition=GPU
#SBATCH --job-name=den25grafAng
#SBATCH --ntasks-per-node=10
#SBATCH --output=outGrafAngden25.out
#SBATCH -o outGrafAngden25.log 
#SBATCH -e outGrafAngden25.txt

#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=natalia.huitzil@cimat.mx
#

# exportar el path hacia los ejecutables de Python
export PATH=$PATH:/opt/anaconda3_titan/bin
source /home/est_posgrado_natalia.huitzil/.bashrc
conda activate compu21

hostname
date
# Ejecutar script

cd /home/est_posgrado_natalia.huitzil/GraficasResul/Metrica/den25RGB

#cd /home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8
#cd/home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8 runner.py
#/home/est_posgrado_natalia.huitzil/.conda/envs/compu21/bin/python3.8 Cluster_Prueba7_Denoising3curvGaussian.py


python MetricAngImgKodim_i_den25.py


date
