#!/bin/bash

#SBATCH --partition=GPU
#SBATCH --job-name=492debU
#SBATCH --ntasks-per-node=10
#SBATCH --output=output492debU.out
#SBATCH -o outfile492debU.log 
#SBATCH -e errfile492debU.txt

#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=natalia.huitzil@cimat.mx
#

# exportar el path hacia los ejecutables de Python
export PATH=$PATH:/opt/anaconda3_titan/bin
source /home/est_posgrado_natalia.huitzil/.bashrc
conda activate compu21

hostname
date
# Ejecutar script

cd /home/est_posgrado_natalia.huitzil/ST2/Prueba49

#cd /home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8
#cd/home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8 runner.py
#/home/est_posgrado_natalia.huitzil/.conda/envs/compu21/bin/python3.8 Cluster_Prueba7_Denoising3curvGaussian.py


#python Cluster_Prueba49_DIP_0_debU_data5.py
python Cluster_Prueba49_VectorialTotalVariation_2_debU_data5.py


date
