#!/bin/bash

#SBATCH --partition=GPU
#SBATCH --job-name=411den25rep3
#SBATCH --ntasks-per-node=10
#SBATCH --output=output411den25rep3.out
#SBATCH -o outfile411den25rep3.log 
#SBATCH -e errfile411den25rep3.txt

#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=natalia.huitzil@cimat.mx
#

# exportar el path hacia los ejecutables de Python
export PATH=$PATH:/opt/anaconda3_titan/bin
source /home/est_posgrado_natalia.huitzil/.bashrc
conda activate compu21

hostname
date
# Ejecutar script

cd /home/est_posgrado_natalia.huitzil/ST2/Prueba41

#cd /home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8
#cd/home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8 runner.py
#/home/est_posgrado_natalia.huitzil/.conda/envs/compu21/bin/python3.8 Cluster_Prueba7_Denoising3curvGaussian.py


#python Cluster_Prueba41_VectorialTotalVariationOPP_1_den25_5p5K.py
#python Cluster_Prueba41_UnknownOperatorV4OPP_2_den25_6p6K.py
#python Cluster_Prueba41_VectorialTotalVariation_0_debU.py
#python Cluster_Prueba41_VectorialTotalVariation_0_debG_30K.py


#python Cluster_Prueba41_UnknownOperatorV4OPP_2_den25_6p9K.py

python Cluster_Prueba41_VectorialTotalVariationOPP_1_den25_5p7K.py


date
