#!/bin/bash

#SBATCH --partition=GPU
#SBATCH --job-name=461debGesp
#SBATCH --ntasks-per-node=10
#SBATCH --output=output461debGesp.out
#SBATCH -o outfile461debGesp.log 
#SBATCH -e errfile461debGesp.txt

#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=natalia.huitzil@cimat.mx
#

# exportar el path hacia los ejecutables de Python
export PATH=$PATH:/opt/anaconda3_titan/bin
source /home/est_posgrado_natalia.huitzil/.bashrc
conda activate compu21

hostname
date
# Ejecutar script

cd /home/est_posgrado_natalia.huitzil/ST2/Prueba46

#cd /home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8
#cd/home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8 runner.py
#/home/est_posgrado_natalia.huitzil/.conda/envs/compu21/bin/python3.8 Cluster_Prueba7_Denoising3curvGaussian.py

#python Cluster_Prueba46_VectorialTotalVariationOPP_0_sinpesOpp.py
python Cluster_Prueba46_VectorialTotalVariationOPP_1_den15_8p3K.py
#python Cluster_Prueba46_UnknownOperatorV4OPP_2_debG_unic_sinpesOpp.py


date
