#!/bin/bash

#SBATCH --partition=GPU
#SBATCH --job-name=DebU382rep
#SBATCH --ntasks-per-node=10
#SBATCH --output=outputdebU382.out
#SBATCH -o outfiledebU382rep.log 
#SBATCH -e errfiledebU382rep.txt

#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=natalia.huitzil@cimat.mx
#

# exportar el path hacia los ejecutables de Python
export PATH=$PATH:/opt/anaconda3_titan/bin
source /home/est_posgrado_natalia.huitzil/.bashrc
conda activate compu21

hostname
date
# Ejecutar script

#cd /home/clirlab/natalia/Prueba37/
cd /home/est_posgrado_natalia.huitzil/ST2/Prueba38/
#cd /home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8
#cd/home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8 runner.py
#/home/est_posgrado_natalia.huitzil/.conda/envs/compu21/bin/python3.8 Cluster_Prueba7_Denoising3curvGaussian.py

#python Cluster_Prueba38_GradientRiemannian_0_20K.py
python Cluster_Prueba38_RiemannianGradientOPP_2_25K_debU.py

date
